components:
 - https://github.com/ldesrosi/gitops-components-library/components/bamoe/services/dependencies/kafka
 - https://github.com/ldesrosi/gitops-components-library/components/bamoe/services/dependencies/postgresql
 - https://github.com/ldesrosi/gitops-components-library/components/bamoe/services/dependencies/keycloak
 - https://github.com/ldesrosi/gitops-components-library/components/bamoe/services/data-index
 - https://github.com/ldesrosi/gitops-components-library/components/bamoe/services/management-console
 - https://github.com/ldesrosi/gitops-components-library/components/bamoe/services/task-console

configMapGenerator:
  - name: bamoe-services-endpoints
    namespace: app-bamoe-services
    literals:
      - KEYCLOAK_URL=https://cluster-keycloak-ingress-keycloak.bamoe-cluster-3cd0ec11030dfa215f262137faf739f1-0000.eu-gb.containers.appdomain.cloud/
      - DATA_INDEX_URL=https://data-index-route-app-bamoe-services.bamoe-3cd0ec11030dfa215f262137faf739f1-0000.eu-gb.containers.appdomain.cloud/graphql/

patches:
- target:
    kind: Keycloak
    name: cluster-keycloak
  patch: |-
    - op: replace
      path: /spec/hostname/hostname
      value: cluster-keycloak-ingress-keycloak.bamoe-cluster-3cd0ec11030dfa215f262137faf739f1-0000.eu-gb.containers.appdomain.cloud/

generatorOptions:
  disableNameSuffixHash: true
  